### ISSUE TITLE
Add next/previous track keys

### ISSUE THREAD

**Issue by Vlek** [keyboardio/Kaleidoscope#1020]
**Is your feature request related to a problem? Please describe.**
I am currently unable to map keys to perform the media functions "play next track" and "play previous track"

**Describe the solution you'd like**
I would like to be able to have an easy-to-use key, named something like Key_MediaTrackNext and Key_MediaTrackPrevious to use in key mapping.

**Describe alternatives you've considered**
Currently available keys may offer some similar functionality, but I am not knowledgeable enough in the different key events to know which would be able to function in the same way as the ones I am requesting.

**Additional context**
None.

**Comment by gedankenexperimenter** [comment]
Have you tried `Consumer_ScanNextTrack` and `Consumer_ScanPreviousTrack`?

**Comment by Vlek** [comment]
That did it for me! Thank you.
