### ISSUE TITLE
Unicode plugin: configurable shortcut (Key_U on Linux)

### ISSUE THREAD

**Issue by BenjaminGalliot** [keyboardio/Kaleidoscope#1063]
Currently, especially on Linux, the Unicode input works with Ctrl+Shift+U, but if the keyboard is on another layout (*bépo*, for example), this letter U will correspond to the letter S, which will return a sequence of wrong simple characters rather than the right Unicode character...

Making this key (or even the whole shortcut) configurable would be useful for some users.

There was a discussion about this on the Discord.

**Comment by algernon** [comment]
The whole thing can be changed by switching to a custom unicode input mode (`HostOS.os(kaleidoscope::plugin::hostos::OTHER)`), and overriding a few methods. Not the most convenient, but for full customisation, that's the way to go. Changing the `u` key, however, to account for different host-side layouts, is something that should be easier, indeed.

I'll have a PR up soon, that will allow you to do: `Unicode.setLinuxKey(Key_S)`. You'll have to figure out which key maps to `u` on Bépo. But it will allow you to change that part of the sequence.
