### ISSUE TITLE
Text link is broken on Core Plugin Overview page for third-party plugins.

### ISSUE THREAD

**Issue by NabiYang** [keyboardio/Kaleidoscope#1096]
**Describe the bug**
Visiting the text link (it isn't hyperlinked) at the end of the introductory section under Core Plugin Overview leads to a page saying the destination page doesn't exist. It also suggests the page may be private, but I signed up for an account and still get the same message.

**To Reproduce**
1. Visit the link for third-party plugins listed under Core Plugin Overview: https://kaleidoscope.readthedocs.io/en/stable/customization/core-plugins.html
2. It leads to a page stating, "Oops! That page doesn’t exist or is private."

**Expected behavior**
I expect to be taken to a page listing third-party plugins.

**Environment (please complete the following information):**
 - OS: macOS
 - 12.0.1

**Additional context**
None.

**Comment by algernon** [comment]
FWIW, the correct link should be [this](https://community.keyboard.io/c/programming/discuss-kaleidoscope-plugins-one-thread-per-plugin/12). I'll push a fix in a bit.

Thanks for noticing the issue! I'll also turn the link into a proper link, rather than a text one has to copy & paste.
