### ISSUE TITLE
Deal gracefully with the right hand being disconnected or reconnected

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#12]

**Comment by obra** [comment]
The current implementation deals much, much more gracefully than it did when this ticket was opened. Resolving

**Comment by mattvenn** [comment]
I'm looking at this at the moment because when I disconnect and reconnect one part of our keyboard there is a high chance it either becomes non responsive or the 32u4 starts reporting a stuck key.
Can you point me to the commit where you did some work on this so I can take a look?

**Comment by obra** [comment]
Our i2c protocol now sends full keymap states rather than events. That was, iirc, the change.
