### ISSUE TITLE
ConsumerControl does not repeat

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#120]
At the moment, `ConsumerControl` keys are not repeating, because we use `ConsumerControl.write()`, and only when the key toggles on. This means that if I want to fiddle with volume control (iirc that is part of `ConsumerControl`, but `SystemControl` suffers from the same issue), I need to repeatedly tap a key, instead of being able to hold it.

I think we should be using `.press()`, and `.releaseAll()` in the loop, like we do for `Keyboard`, but I have to test if this works as one would expect.

**Comment by obra** [comment]
Note that the switch to write is a recent change. Until recently, the way we were doing it would cause even the briefest tap to send so many events to the host that it would overwhelm it with repeats. The specific symptom is that tapping the volume up key briefly on a mac would push it up to max volume and send so many extra events, volume couldn't be dropped back down.

This may be something where we want to handle CC events marked "OSC" (one shot control) differently than others.

**Comment by algernon** [comment]
Mhm, I suspected that may be behind the behaviour. I'll see what / how other keyboards do it, and experiment a bit.

**Comment by algernon** [comment]
Ah, there we go. Problem with the previous implementation, which only used `.press`, was that it never released the key. Merely changing `.write` to `.press` does, indeed, exhibit the problem you described, and the key remains "stuck" forever. If I add an explicit `.release` when the key toggles off, it all works fine.
