### ISSUE TITLE
Make the boot greeting LED color configurable

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#1200]
This is something keyboardio needs for the Model 100's factory firmware

**Comment by algernon** [comment]
I went ahead to implement it, but... it already supports setting a different color. We just need to set `BootGreetingEffect.hue` in `setup()`.

**Comment by gedankenexperimenter** [comment]
Interesting.  Somehow I missed some plugins when deprecating public variables…

**Comment by algernon** [comment]
Excuse my stupid joke, but I failed the saving throw: I suppose this particular one stayed hidden, because it only greets you for a few seconds after booting, and you were looking for public variables post-coffee, so post-boot, and this one flew under the radar then.
