### ISSUE TITLE
PrefixLayer does not work with more than one prefix layer.

### ISSUE THREAD

**Issue by LemonBreezes** [keyboardio/Kaleidoscope#1324]
With this config snippet, only the first prefix layer works:
![image](https://user-images.githubusercontent.com/29102529/212183242-bd162317-6ae6-4c7a-b79d-42564014e29f.png)

![image](https://user-images.githubusercontent.com/29102529/212183287-dc4b1756-be3f-42ac-8479-daf1f279f6be.png)
Manually editing the `prefix_layers_length_` in the highlighted line of code to 3 fixes this issue for me so I believe the length is not being calculated correctly.

I'm using a Model 100 and I'm on the latest master branch of Kaleidoscope.

**Comment by gedankenexperimenter** [comment]
There's an error in `setPrefixLayers()`, which I'm pretty sure I can fix with a template.

**Comment by gedankenexperimenter** [comment]
I'm pretty sure I've got this one worked out; I just need to write a testcase for multiple prefix layers.
