### ISSUE TITLE
Colormap example does not work

### ISSUE THREAD

**Issue by nicos68** [keyboardio/Kaleidoscope#1354]
The Colormap.ino source code that can be found under `examples/LEDs/Colormap` does not behave as expected.

 - Compile the source code of `Colormap.ino`
 - Flash the binary to the keyboard

**Expected behavior**
 - The colors defined in the Colormap.ino source code are applied to the keyboard's LEDs

**Actual behavior**
 - Seemingly random colors are applied to the keyboard's LEDs.
 - When running Chrysalis the colors displayed by the tool acutally match the keyboard LEDs' colors:
![image](https://github.com/keyboardio/Kaleidoscope/assets/1062625/1904673d-7322-4b81-bb71-f5b86b5859c2)
 - after a few seconds the LEDs of the keyboard's right half turn off.
 - If I use chrysalis to change a led color, it actually gets applied to the keyboard's LEDs

**Environment (please complete the following information):**
 - OS: Fedora
 - Version 38
 - Device Keyboardio Model 01

**Additional context**
- When doing a factory reset, no matter what color I set using Chrysalis, it never gets applied to the keyboard's LEDs
- No matter what colors I pass to the `COLORMAP` function call as argument on line 80, the same random colors get applied to the keyboard.

**Comment by nicos68** [comment]
So it looks like I have to run the backup script after flashing for the colormap plugin to work, that’s confusing but well, I found a solution.

**Comment by obra** [comment]
I'm glad you got it sorted out. I'm not quite sure what caused the weird
behaviour you're seeing. If you get it stuck again, please let us know.

Can you tell me which backup script you were using and whether you flashed
with Chrysalis or with 'make flash' from the commandline?

Best,
jesse

**Comment by nicos68** [comment]
- I use kaleidoscope’s eeprom-backup script
- I flash my keyboard
  - Using Chrysalis when I make simple keymap changes
  - Using [arduino-cli](https://arduino.github.io/arduino-cli/0.35/) when I make code changes to the firmware code. See the flash (and compile) recipe in [my justfile](https://codeberg.org/nise/Model01-Firmware/src/commit/f93e862a8d7579bbdb8c4df5040f757102e58839/justfile#L13)

**Comment by obra** [comment]
indeed, if you are storing things in the on devices storage, you should
either be using Chrysalis to do your flashing or always be doing an EEPROM
back up and restore on the the two sides flashing

**Comment by nicos68** [comment]
Well, I would expect things to fix themselves when I execute the restore script, but that's not what happens :
 * I added the colormap plugin to my firmware code
 * I compiled the firmware
 * I flashed the new firmware with colormap and my color settings => The random colors showed up and my colormap settgins were ignored
 * I ran the backup scrip => then immidiately my colormap settings were applied to the keyboard. I did not run the restore script.

**Comment by obra** [comment]
That’s odd. You *should* need to run the backup before flashing

**Comment by nicos68** [comment]
It works like that everytime now. If I change the colormap in my firmware, then compile and flash, the color change is ignored. Then when I run the backup script the colormap change is correctly applied.
