### ISSUE TITLE
xon/xoff flow control may be stalling out waiting for more input.

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#1367]
@tlyu says: xon/xoff from Focus are acting weird in ways i haven’t quite characterized yet. sometimes Focus will send an xoff but not send an xon for a long time, sometimes only after it gets more input!

![image](https://github.com/keyboardio/Kaleidoscope/assets/45416/6556f33e-f6bc-4c71-9cb8-e7a232e59df7)
We almost certainly want to manage flow control on both sides of those reads.

**Comment by tlyu** [comment]
Fixed by #1369 and #1370.
