### ISSUE TITLE
Print firmware location when running `make compile`

### ISSUE THREAD

**Issue by EvyBongers** [keyboardio/Kaleidoscope#1415]
**Is your feature request related to a problem? Please describe.**
Currently, when using make files to build a custom sketch, users have no feedback where the resulting binaries are stored. This isn't a problem when flashing using `make flash`, but for users who want to flash their firmware using Chrysalis, this is a poor experiencee

**Describe the solution you'd like**
And update to the makefiles (probably `etc/makefiles/sketch.mk`) to print the location of the resulting files.

**Describe alternatives you've considered**
As `make compile` results in a few files, the make file could print either the directory that contains all the resulting files or just the path to the file needed to flash the firmware using Chrysalis.

**Additional context**
https://discord.com/channels/492408953041321984/492907083583455246/1220807598748602419

**Comment by obra** [comment]
Closing, as @EvyBongers implemented this
