### ISSUE TITLE
Going in and out of numpad mode often sets the led color to red

### ISSUE THREAD

**Issue by chughes87** [keyboardio/Kaleidoscope#145]
Regardless of what the previous setting was, the keyboard will be in the red state after going in and out of numpad mode. This doesn't 100% consistently happen though. It seems to happen the first time after logging back into my computer but not again until I log out of my computer and come back to my desk later. So the problem may be with persisting the selected color scheme during computer sleep states?

**Comment by obra** [comment]
On Wed, Jul 26, 2017 at 08:31:46PM +0000, Charles Hughes wrote:
>    Regardless of what the previous setting was, the keyboard will be in the
>    red state after going in and out of numpad mode. This doesn't 100%
>    consistently happen though. It seems to happen the first time after
>    logging back into my computer but not again until I log out of my computer
>    and come back to my desk later. So the problem may be with persisting the
>    selected color scheme during computer sleep states?

There are patches that landed a couple days ago to fix this. Are you
currently running stock firmware or have you reflashed in, say, the last
36 hours?

**Comment by chughes87** [comment]
oh I haven't reflashed yet. I will try this later and let you know if it resolves the issue. Thanks!

**Comment by obra** [comment]
On Wed, Jul 26, 2017 at 08:39:13PM +0000, Charles Hughes wrote:
>    oh I haven't reflashed yet. I will try this later and let you know if it
>    resolves the issue. Thanks!
> 

Great. Thanks.

**Comment by chughes87** [comment]
This was resolved after flashing 👍
