### ISSUE TITLE
Reset mouse acceleration when mouse key is released

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#15]

**Comment by algernon** [comment]
This one is mighty annoying. I'll submit a PR soon-ish.

**Comment by algernon** [comment]
I believe this has been fixed for a while, and is certainly fixed on `Keyboardio-MouseKeys` [master](https://github.com/keyboardio/Keyboardio-MouseKeys/blob/ba1a8604a07f32359e56c0982b0f2b0d81ebc96c/src/Keyboardio-MouseKeys.cpp#L15-L18).
