### ISSUE TITLE
Can the prog key be bound?

### ISSUE THREAD

**Issue by jyp** [keyboardio/Kaleidoscope#160]
In the default configuration, the 'Prog' key is not bound to anything. Is this necessary to be able to flash the firmware in the "easy" way? Or can it be bound without any loss of functionality?

**Comment by algernon** [comment]
It can be bound to anything you like without any loss of functionality.

It is the bootloader that checks if that key is pressed when you flash it, not the firmware itself, so whatever you bind it to, doesn't matter. For the same reason, you can't bind the flash-enabling functionality to any other key.

**Comment by jyp** [comment]
Great, thanks!
