### ISSUE TITLE
Document Kaleidoscope hardware backend API

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#167]
We need to formalize the API exported by Kaleidoscope hardware implementations. Currently, the gold standard is Kaleidoscope-Hardware-Model01. @algernon is working on a new base class for that to inherit from. Once we have that, every API method should have doc on use case, calling convention and valid inputs/outputs.

**Comment by algernon** [comment]
Since I'm working on the base class anyway, I'll assign this to myself, so I remember to write docs too.

**Comment by algernon** [comment]
I have started working on [Kaleidoscope-Hardware](https://github.com/keyboardio/Kaleidoscope-Hardware), a base class for all hardware plugins. It has at least some docs, but will likely need some improvements.

**Comment by cdisselkoen** [comment]
This can probably be considered resolved by https://github.com/keyboardio/Arduino-Boards/commit/acaa674f75a525f0b553d32ecf7ceab8892ff669

**Comment by cweagans** [comment]
Kaleidoscope-Hardware is a good first step, but I'd also like to see some information about the high-level stuff that one needs to do in order to port this firmware to other hardware. I'm interested in porting Kaleidoscope to the Ergodox Infinity, but I have no idea where to start.
