### ISSUE TITLE
Document API available to plugins

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#169]
We need a technical document, aimed at plugin authors, which describes:

* The hooks available to a plugin
* The API available to a plugin. (Including things like keypresses and LEDs and hardware state)
* APIs, if any, we consider off limits to plugins

**Comment by gedankenexperimenter** [comment]
I think this issue has been adequately addressed.

**Comment by obra** [comment]
I'm ok closing this out, though would be thrilled to have more specific issues opened for missing bits of doc.
