### ISSUE TITLE
docs migrated to wiki- what to do with old docs?

### ISSUE THREAD

**Issue by Jennigma** [keyboardio/Kaleidoscope#210]
The content of the docs file, minus my outline of things to write, has been split into three parts and shifted to the kaleidoscope wiki. 

I will sort out formatting the table of contents as my next task, then continue down my outline.

Should we delete the DRAFT monolithic file in doc that I was previously working in? it's redundant. 

Might be sensible to have a small file in doc pointing folks to the wiki for documentation.

**Comment by obra** [comment]
Kill it. I'd say that pointers to docs could live happily in README

**Comment by Jennigma** [comment]
Done.
