### ISSUE TITLE
where to store images for docs?

### ISSUE THREAD

**Issue by Jennigma** [keyboardio/Kaleidoscope#211]
I would like to be able to add images to the docs. I see that @obra used his own repo for the images in the bootloader page of the wiki:

https://github.com/obra/KeyboardioFirmware/wiki/images/

I prefer not to believe that my repo will persist indefinitely, and if there is a way for me to add images to the main wiki/images/ directory, I haven't found it. I would welcome help figuring it out.

I could create a docs/images directory and reference that.

Suggestions?

The proximal problem is sharing images of the Dvorak and Colemak layouts. I have saved nice .png's from the .svg, just need a place to put them.

**Comment by obra** [comment]
You should be able to check out the Kaleidoscope wiki as a git repo and add
the images as files to it.

**Comment by Jennigma** [comment]
got it working.
