### ISSUE TITLE
Feature request: a capslock LED mode that works analogous to the numlock LED mode

### ISSUE THREAD

**Issue by Soares** [keyboardio/Kaleidoscope#219]
See also https://community.keyboard.io/t/has-anyone-already-written-a-capslock-led-mode-analogous-to-the-numlock-led-mode/555

**Comment by lydell** [comment]
A similar request: I’ve made a custom base layer. I use the Prog key to switch to the standard QWERTY layer, by setting the Prog key to `LockLayer(QWERTY)` in my custom layer and to `UnlockLayer(QWERTY)` in the QWERTY layer. I’d like the Prog key to be lit in blue when I’ve switched to QWERTY mode.

**Comment by algernon** [comment]
@lydell That's reasonably easy to accomplish, and does not need a new plugin, with something like the following:

```c++
void QWERTYLEDHook(bool post_clear) {
  if (post_clear)
    return;

  if (Layer.isOn(QWERTY))
    LEDControl.SetCrgbAt(0, 0, CRGB(0, 0, 255));
  else
    LEDControl.refreshAt(0, 0);
}

void setup() {
  // ...
  Kaleidoscope.useLoopHook(QWERTYLEDHook);
}
```

**Comment by lydell** [comment]
@algernon Thanks! That’s exactly what I needed! Just one small typo in there; it’s supposed to be `setCrgbAt` with a lowercase “s”. Sorry for hijacking the thread!

**Comment by Soares** [comment]
I see this issue has been closed. Hooray! @algernon, would you mind giving me a brief summary of the right way to make caps-lock color the letters (but not the numbers) when activated, in analogy with numlock?

**Comment by algernon** [comment]
@Soares Oops, closing was a mistake, as I did not explain the original question. Sorry!

I suppose the easiest would be to iterate over the keymap, find any keycodes between `Key_A` and `Key_Z`, and color those and those only. Something along these lines:

```c++
bool capsState = !!(kaleidoscope::hid::getKeyboardLEDs() & LED_CAPS_LOCK);

if (capsState) {
  for (uint8_t r = 0; r < ROWS; r++) {   
    for (uint8_t c = 0; c < COLS; c++) {
      Key k = Layer.lookupOnActiveLayer(r, c);

       if ((k.raw >= Key_A.raw) && (k.raw <= Key_Z.raw)) {
          LEDControl.setCrgbAt(r, c, CRGB(0, 0, 255));
        } else {
          LEDControl.refreshAt(r, c);
        }
    }
  }
}
```

Add this to your `loop` method, and it should do the trick.

**Comment by Soares** [comment]
Thanks!

**Comment by donfeduardo** [comment]
I've written a plugin with this functionality: [Kaleidoscope-CapsLock](https://github.com/donfeduardo/Kaleidoscope-CapsLock).
