### ISSUE TITLE
Document all Kaleidoscope hooks, with their inputs, outputs and hook points

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope#231]
Basically, the API for plugins needs a writeup.

**Comment by gedankenexperimenter** [comment]
I'd label this as "bug" and "docs" as requested, but I don't have permission to do that.

**Comment by cdisselkoen** [comment]
This is also essentially a duplicate of #169.

**Comment by algernon** [comment]
...that indeed it is. Added the labels there, and am closing this one.
