### ISSUE TITLE
Keyboard doesn't respond to keypresses when Windows session is locked

### ISSUE THREAD

**Issue by kajsa** [keyboardio/Kaleidoscope#237]
When I come back to my desktop machine after a time away (long enough that Windows puts it to sleep), none of the buttons on the Model 01 register keypresses unless I unplug the keyboard and plug it back in.

I noticed this morning that the LEDs were still glowing, and still shifting through the rainbow cycle. To try to get some more information, I set the LED mode to Stalking, turned the sleep timeout down, and stepped away. Coming back, I can see based on the LED behavior that the board is processing keypresses, but not communicating them to the host.

I should note that this just started happening recently, and that my Arduino-Boards repo is currently at 67d6b23. I haven't sat down and bisected to figure out where the problem was introduced, but I could (it'd just take a while, since test cycles would involve both flashing the board and waiting for the host to go to sleep).

**Comment by wez** [comment]
FWIW, in my experiments with suspend/sleep modes I found that the arduino usb stack did not survive coming back from sleeping the CPU.  The LUFA implementation works just fine, but isn't an option for arduino.  I'd recommend avoiding putting the controller to sleep if possible.  I haven't been following the core of the kaleidoscope firmware very closely recently, so I don't know if this is something changed in the kaleidoscope code or something that may have changed in arduino itself.

**Comment by kajsa** [comment]
Interesting. Since I'm dealing with a desktop, I can certainly set it not to go to sleep as a workaround.

**Comment by obra** [comment]
Indeed, I spoke to a domain expert today and got similar advice. the amount of power we burn even without sleep is...small. simply defaulting to turning off the LEDs would be 90-98% of all the possible power management win.

**Comment by algernon** [comment]
I got to the point that I can wake the host up after it suspended, under Linux. Needed to explicitly enable wakeup, it didn't enable automatically. I suppose that the same is possible under Windows, allowing wakeup on a per-device basis.

It would be better if we could Just Do That(tm) automatically, and am trying to figure out how to enable remote wakeup by default.

**Comment by algernon** [comment]
The [MyOldFriend](https://github.com/keyboardio/Kaleidoscope-MyOldFriend) plugin has a fix for this, I hope. It allows the keyboard to wake the host up on Linux at least. I have not tested any other platforms yet, but have my fingers crossed.

**Comment by algernon** [comment]
This has been fixed by keyboardio/Model01-Firmware#41.
