### ISSUE TITLE
kaleidoscope::hid implicitly enables mouse & absmouse nodes

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#257]
The `kaleidoscope::hid` facade implicitly enables the `Mouse` and `SingleAbsoluteMouse` nodes, even when MouseKeys aren't used. This has two implications:

- Mouse stuff is compiled in, even when `MouseKeys` are unused.
- Some operating systems do not support keyboard and mouse on the same node (looking at you, [FreeBSD](https://github.com/freebsd/freebsd/blob/d8596f6f687a64b994b065f3058155405dfc39db/sys/dev/usb/input/ukbd.c#L1050-L1056)), and prefer the mouse. In our case, the keyboard part is much more important. Building a firmware without `MouseKeys` should not create the mouse endpoints, otherwise these OSes won't work at all.

One reasonable approach would be to move the mouse bits out of Kaleidoscope, and into `Kaleidoscope-MouseKeys`, keeping them in the same namespace.

**Comment by obra** [comment]
What about moving the mouse to another endpoint?

**Comment by algernon** [comment]
That may also work, but IIRC we can only have four endpoints. With keyboard + mouse + absolutemouse + serial, we max that out.

On the other hand, even when on another endpoint, we still shouldn't compile it in when not needed.

**Comment by algernon** [comment]
Had an attempt at moving the mouse parts of `kaleidoscope::hid` to `MouseKeys`: utter failure. All kinds of linker errors unless I explicitly use `Mouse.begin` / `AbsoluteMouse.begin` in the sketch.

Perhaps this hid facade needs to be rethought...

**Comment by algernon** [comment]
keyboardio/KeyboardioHID#11 addresses the most important part of this, allowing one to build a `Mouse`-less firmware. `SingleAbsoluteMouse` is still compiled in, but as that is on a different node, it is less of an issue.
