### ISSUE TITLE
Stuck in fn mode

### ISSUE THREAD

**Issue by adkron** [keyboardio/Kaleidoscope#266]
I don't know how to reproduce this. I was typing away on my keyboardio, and trying to diagnose another issue, so I am on the default firmware. All of the sudden all my keys start acting like the `fn` key is depressed. When I do hold down the `fn` key it acts like the key is not depressed and I get regular typing again. I've tried to reproduce it in a number of ways and none are successful.

https://community.keyboard.io/t/stuck-in-function-layer/858

**Comment by algernon** [comment]
I believe this has been fixed for a while. @adkorn do you still have this issue?

**Comment by adkron** [comment]
I haven't seen this in a long time.
