### ISSUE TITLE
Is there a way to make left and right function key only switch that half of device?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [keyboardio/Kaleidoscope#307]
Was trying to play a simple game with cursor keys and z and x and cant press them whilst using cursor.
maybe a way to remap to a game mode whilst its running would be good similar to how numpad can be activated.

ill do some more reading and try to flash firmware soon

cursor keys separate would have been very useful.

**Comment by gedankenexperimenter** [comment]
You could have two layer — one with a transparent left side, on with a transparent right side. Then, on the base layer, one palm key is mapped to `ShiftToLayer(FN_LEFT)` and one to `ShiftToLayer(FN_RIGHT)`.

**Comment by LiamKarlMitchell** [comment]
Great replies thanks.

**Comment by algernon** [comment]
As there were a few useful answers provided, I think we can consider this question answered. I'm closing the issue, but feel free to reopen it (or open a new one) if you still have questions, or need help with setting up your sketch the way you want.
