### ISSUE TITLE
CI considerations

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#358]
First of all, this is a very, very minor thing, for a rainy day months (years?) down the road.

I'm not too happy with Travis lately, mostly due to having issues with it in my other projects. I recently set up a [Drone CI](https://drone.io) for my own needs, and been so happy with it, that everything is starting to look like a nail now, Kaleidoscope included.

Anyway, what Drone provides is more control, better/easier to manage environments. I won't go into much more detail here, we should do that if/when we get to a stage where we can afford thinking about spending resources on researching CI systems. Things might change drastically 'till then.

Nevertheless, CI/CD is something that's been on my mind lately, an area we could improve at, so let this issue serve as a kind of placeholder.

**Comment by obra** [comment]
Closing for now, as Travis does appear to still be suiting our needs. If we -do- move to something else, I'm betting GH Actions is likely to be our new pony.
