### ISSUE TITLE
Qukeys: Implement per-qukey release delay overrides

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#397]
Originally by @gedankenexperimenter, as keyboardio/Kaleidoscope-Qukeys#37.

**Comment by gedankenexperimenter** [comment]
If the new rollover algorithm in #640 works well enough, I think this issue can be closed.

**Comment by gedankenexperimenter** [comment]
I don't intend to do anything more on this; I think the issue should be closed.
