### ISSUE TITLE
NOTICE and LICENSE mismatch (simple fix)

### ISSUE THREAD

**Issue by silverhook** [keyboardio/Kaleidoscope#4]
I noticed that the `LICENSE` file now says GPLv2, which seems fine.

But the `NOTICE` file still mentions that the Keyboard.IO driver is licensed under the Apache 2.0.

I’d suggest you update the NOTICE file to point to the right license.

Since `NOTICE` file is not needed under GPL (but is needed if you contribute to an Apache Foundation project), it might even make sense to change the `NOTICE` file to `README` or `README.markdown`. Feel free to keep the filename as it is, if that suits your style better. Not a biggie there :smile_cat:

**Comment by obra** [comment]
Thanks. (Our ideal is to license under apache 2.0, but the LED driver
we're currently using is GPL-only.)

I've removed the conflicting statement from NOTICE, but left the file, 
as it describes the provenance of the arduino core. Other third-party
code should be noted there as well



On Sat, Oct 31, 2015 at 11:21:25AM -0700, Matija ??uklje wrote:
>    I noticed that the LICENSE file now says GPLv2, which seems fine.
> 
>    But the NOTICE file still mentions that the Keyboard.IO driver is licensed
>    under the Apache 2.0.
> 
>    I’d suggest you update the NOTICE file to point to the right license.
> 
>    Since NOTICE file is not needed under GPL (but is needed if you contribute
>    to an Apache Foundation project), it might even make sense to change the
>    NOTICE file to README or README.markdown. Feel free to keep the filename
>    as it is, if that suits your style better. Not a biggie there
>    [1]:smile_cat:
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    2. https://github.com/keyboardio/KeyboardioFirmware/issues/4
>    3. https://github.com/keyboardio/KeyboardioFirmware/issues/4

--

**Comment by silverhook** [comment]
OK, I understand your idea.

The issue is that now the `NOTICE` file looks as if you apply full copyright on your driver, which could be interpreted as conflicting with the license.

We can look into this later on when we both have time, especially since, as I understand, you’re rewriting the firmware.

I haven’t checked it in great detail, but if you’re referring to the code in `hardware/keyboardio/avr/` – most of that stuff looks under **LGPL-2.1+** (GNU Lesser General Public License, version 2.1 or later). That license does not extend to the whole project, since it limits itself to the “library”.

I can look into the licensing options, if that’d help you guys. If so, it’d help to know what the reasons are for your choice of Apache 2.0 and what you’d like to achieve with your license.

**Comment by obra** [comment]
The NOTICE file has been removed
