### ISSUE TITLE
OneShot: Repeat feature disappears after first layer oneshot cycle

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#415]
Originally by @BenjaminGalliot, as keyboardio/Kaleidoscope-OneShot#39.

**Comment by algernon** [comment]
This is... getting complicated. It's easy to reproduce:

- Double-tap a one-shot layer key
- Observe that keys on the layer repeat
- Turn the sticky layer off
- Hold it (or double-tap it) again
- Observe that keys on the layer do not repeat anymore

I can only reproduce this after a sticky layer has been enabled once, not when just holding one long.

Funnily enough, all OneShot states appear to be the same in both cases.

**Comment by algernon** [comment]
HAH. GOTCHA! Found the responsible code, now trying to figure out *why* normal, interrupting keys result in a masking. Probably a workaround for some rollover thing, which we may have fixed before.

**Comment by algernon** [comment]
Ok, so this dates back to keyboardio/Kaleidoscope-OneShot#4, and this was a legitimate workaround at the time. Since then, we improved key lookup, and the case described in that report no longer apply: in case we hold the interrupting key, it will repeat the key that was on the oneshot layer, instead of repeating what's on the layer with the oneshot layer removed.

In other words, if we have `A` on the base layer, `B` on `TEST`, and we trigger `OSL(TEST)` (and do not hold the key), press the other key and hold it, it will repeat `B` instead of inputting `B` and repeating `A` as were the case in the aforementioned issue.

For this reason, I think we no longer need the masking at all, and it can be safely removed. Even in the `OSM` case, removing the masking does not cause any issues.

**Comment by jamadagni** [comment]
Why is this marked “pending” if the PR has been pulled and fixes the bug?

**Comment by algernon** [comment]
Because there's no automation that removes the tag, and it got the pending before being merged.
