### ISSUE TITLE
OneShot: Very short keypress does not trigger OneShot

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#418]
Originally by @Phlogistique, as keyboardio/Kaleidoscope-OneShot#36.

**Comment by algernon** [comment]
@Phlogistique, can you check if this issue still presists with the current git master of Kaleidoscope? I noticed the same problem before, but after #437, I do not see it anymore.

**Comment by gedankenexperimenter** [comment]
I'm pretty sure this has been fixed. I'm even more certain that it's not a bug in #905.

**Comment by obra** [comment]
Closing as obsolete. @Phlogistique - if this is still an issue, please feel free to re-open.
