### ISSUE TITLE
Support more than 128 LEDs in a single board

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#433]
As of #432, the number of LEDs in a board is limited to 128, because we use an `int8_t` as an index. While improbable right now, there might come a time when we meet a board with more than 128 LEDs, in which case an `int8_t` will not suffice.

We should figure out something about that.

**Comment by mattvenn** [comment]
Dygma Raise has more than 128 LEDs!
I've recently run into this issue with trying to get the color map configurator stuff working.

**Comment by algernon** [comment]
With #710 and #695, this should be resolved, but I will verify when I had a chance to test on my Raise PCB.

**Comment by algernon** [comment]
It appears that this is indeed fixed on master.
