### ISSUE TITLE
Think about transitioning docs to a ReadTheDocs-style thing

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#495]
Following up on @obra's comment in #494, we should probably start thinking about making our documentation easier to consume, more presentable, etc.

**Comment by algernon** [comment]
With https://kaleidoscope.readthedocs.io, I think this is pretty much covered? Not completely done yet, but probably on the right track.

**Comment by obra** [comment]
I'd argue that it's "in progress" - most of the wiki content still needs to get moved over there.

**Comment by obra** [comment]
Happy to close this out. We can open new issues for specific bits of content.
