### ISSUE TITLE
Integrate "NullReporter" as a plugin

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#496]
We had an interesting discussion on Discord with @ashkitten, who wanted a way to input the same key super-fast, without relying on the automatic repeat feature of the operating system. @obra suggested a fairly easy way to achieve this: send an empty report at appropriate times!

I came up with a half-baked solution, which @ashkitten tweaked further [here](https://gist.github.com/ashkitten/1f184a99ece0eca53d5c8f266419cc8c). We should turn this into a proper plugin, with documentation and all that.

**Comment by algernon** [comment]
Oh, the name: NullReporter is a terrible name. It was fine when it was a quick hack, but it's not a good name for the plugin. As @ashkitten suggested on Discord, something based on "Turbo" would be much more fitting.

**Comment by obra** [comment]
TurboKeyRepeat?
ᐧ
