### ISSUE TITLE
Add functions for determining if *any* modifier is active

### ISSUE THREAD

**Issue by tiltowait** [keyboardio/Kaleidoscope#532]
As is discussed [here](https://community.keyboard.io/t/trying-to-understand-key-flags-and-onkeyswitchevent/2435/2), while we can ask the keyboard if a *specific* modifier is/was active, there is currently no friendly API for asking if *any* modifier is/was active. The only way to do so is fairly obtuse:

```c++
if(Keyboard.lastKeyReport.modifiers > 0) {
  // Do stuff
}
```

There are times where a plugin might want to know if *a* modifier is active without caring *which* modifier is active. I propose a pair of new functions, `hid::isAnyModifierKeyActive()` and `hid::wasAnyModifierKeyActive()`. Example usage:

```c++
if(hid::wasAnyModifierKeyActive()) {
  // Do stuff
}
```

This is far more readable than the earlier snippet and much more efficient than querying the keyboard on eight different individual modifiers.

See related PRs in [KeyboardioHID](https://github.com/keyboardio/KeyboardioHID/pull/48) and [Kaleidoscope-HIDAdaptor-KeyboardioHID](https://github.com/keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID/pull/14).

**Comment by tiltowait** [comment]
I'm not opposed to the idea in principle, but it does introduce inconsistency between `is/wasModifierKeyActive()` and, say, `isKeyPressed()`.

**Comment by algernon** [comment]
I agree with @tiltowait, while keeping the API surface small is a good goal, we should also strive for consistency, and overloading `wasModifierActive()` with this new functionality, and not doing the same for `isKeyPressed()` would be wrong. *If* we did it for `ifKeyPressed()` too on the other hand, then I think I'd support that.

**Comment by tiltowait** [comment]
> _If_ we did it for `ifKeyPressed()` too on the other hand, then I think I'd support that.

Anticipating that this might indeed be the route undertaken, I took a look at overloading both `isKeyPressed()` and `wasKeyPressed()`. I feel like I'm a little out of my depth here. `BootKeyboard_` looks straightforward enough; a reading of `press()` and `release()` suggests the following should suffice:

```c++
boolean BootKeyboard_::isKeyPressed() {
  return lastKeyReport.keys[0] == 0x00;
}
```

But for `Keyboard_`, I have to admit I'm not entirely sure what's going on.

Additionally, the `hid` namespace is missing the present `is/wasKeyPressed()` API. Is this an oversight?

**Comment by algernon** [comment]
> I think I understand now what's going on in Keyboard_. Would the no-argument `isKeyPressed()` simply have to check if *all* the elements in `keyReport.keys` are 0?

Yes. Do keep in mind that this was just my idea, @obra needs to approve it before we go that way.

**Comment by tiltowait** [comment]
I'm aware.

**Comment by obra** [comment]
I can see how my implementation could cause hard-to-debug bugs if someone
accidentally passed an empty modifier in.

I'm now feeling bad about 'activated' and 'pressed' being used for two
different kinds of keys (modifiers and regular keys). Is that something we
should fix as we add new 'modifier' related methods?

**Comment by tiltowait** [comment]
I'm ambivalent about `Active` vs. `Pressed`. While I can see that it might be a source of some minor confusion that they have different names, it also accurately reflects that modifiers and regular keys are used differently.

I think a greater potential source of confusion is that `isKeyPressed()` returns `false` if a modifier key is passed to it. I assume it's done this way for performance reasons.

**Comment by obra** [comment]
Oh, I'm 99.9% sure it's done that way because it was a mistake inherited
from our upstream.
ᐧ

**Comment by obra** [comment]
Sorry I've let this hang out for a bit. Upon reflection, I think I'm good with it as implemented.
