### ISSUE TITLE
`make clean` doesn't seem to do anything

### ISSUE THREAD

**Issue by tiltowait** [keyboardio/Kaleidoscope#542]
`kaleidoscope-builder` has the `clean` function:

```sh
clean () {
    rm -rf -- "${OUTPUT_PATH}"
}
```

However, running `make clean` removes nothing, and adding an `echo $OUTPUT_PATH` to the top of the function results in an empty line. I've discovered that adding a call to `build_version` correctly sets the `$OUTPUT_PATH` variable, and `make clean` works as expected.

Is this an issue in my configuration? If so, I'd like to know where I can start looking (and what info is needed from me) to nail down the problem.

**Comment by algernon** [comment]
`build_version()` should be automatically called by `compile()`, unless you overrode that function.

To be honest, I wouldn't dig too deep into this, as we're likely going to replace the CLI build system (including `kaleidoscope-builder`) with something nicer. (See #517)
