### ISSUE TITLE
Reminder: Deprecated Layer methods due for removal

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope#577]
The UPGRADING document sets the removal date for deprecated `Layer` methods as **2019-02-14**:

See here: https://github.com/keyboardio/Kaleidoscope/blob/master/UPGRADING.md#removal-of-layerdefaultlayer

**Comment by algernon** [comment]
Thanks for the reminder, I completely forgot that we have removals due!

**Comment by gedankenexperimenter** [comment]
I just happened across it because I was looking at a PR for PrefixLayer.
