### ISSUE TITLE
System Control keys don't work

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope#607]
I've only been able to test this fully on one iMac (running Mojave), and only with the `System_Sleep` key, but I've found that the OS doesn't respond to the HID report for that keycode unless it's held for some time (maybe even a full second). However, Kaleidoscope always sends two HID reports when a System Control key toggles on – one to signal that the key is pressed, and then another one immediately after, releasing the key.

I've got an alternate firmware that doesn't send the release HID report until the key toggles off, and that actually triggers the dialog that lets me put the machine in "sleep" mode (or power down, or restart). I found out that I need to press and hold the key from [this thread on Reddit](https://www.reddit.com/r/olkb/comments/4vgk3a/sleeppower_key_on_mac/).

I don't know how universal this is, but I can say that on both of the machines that I have handy to test with (the aforementioned iMac and a ten-year-old Ubuntu machine), none of the System Control keys I've tried in Kaleidoscope have had any visible effect.

**Comment by obra** [comment]
I've replicated this issue. At a protocol level, I've verified that we're only ever sending the "press" event in a packet immediately before we send the release event.  And we're only sending it -upon- release. That's 100% wrong.
