### ISSUE TITLE
Enter key triggers twice sometimes

### ISSUE THREAD

**Issue by kevinkjt2000** [keyboardio/Kaleidoscope#624]
#180 has instructions on how to perform the factory test mode, so I gave that a try:

All the keys on my keyboard have the green light quickly changing to blue and staying blue, except for the enter key.  The enter key lights up green while it is actuated, but instead of changing to blue on release, it goes back to red.

Additionally, I do not notice any double triggers if I press the enter key softly.  When I press it slightly harder than normal, I can reproduce the issue 9/10 attempts.

I am assuming this might be a hardware issue.  What could I do to fix it?

**Comment by noseglasses** [comment]
If it is a hardware problem, you might want to contact help@keyboard.io

**Comment by kevinkjt2000** [comment]
I went ahead and sent an email, but I will leave this open in the case that there may be a software fix that I do not know about.

**Comment by obra** [comment]
This is a hardware issue that we're handling through  help@. I'm resolving this ticket.
