### ISSUE TITLE
Possible LED index out of boundes in Model01::getCrgbAt

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/Kaleidoscope#660]
@obra, is the following line correct or does it need to read `if (i < 0 || i >= 64)`?
https://github.com/keyboardio/Kaleidoscope/blob/0ee41c85b42185cdf69b078060b1e69d5fd31586/src/kaleidoscope/hardware/keyboardio/Model01.cpp#L130

**Comment by obra** [comment]
Yeah, the current code looks wrong.
