### ISSUE TITLE
Wiki pages on changing layout in Arduino need to be tweaked to match (newer) instructions in firmware

### ISSUE THREAD

**Issue by ym-han** [keyboardio/Kaleidoscope#671]
e.g., the procedure in https://github.com/keyboardio/Kaleidoscope/wiki/Common-Alternate-Layouts is a little different from that described in the firmware. The firmware procedure is simpler (assuming that the layout one is switching to is either dvorak or vanilla colemak).

I'll try to see if I can tweak the wiki too, but no promises. I think the ideal thing to do would be to note right away on https://github.com/keyboardio/Kaleidoscope/wiki/Edit-A-Keymap that there's this simpler method described in the firmware, and to edit the common alt layouts page (https://github.com/keyboardio/Kaleidoscope/wiki/Common-Alternate-Layouts) accordingly. I also wonder if it might make more sense to combine both pages; they are certainly related enough.

**Comment by obra** [comment]
This change happened some time ago. Resolving.
