### ISSUE TITLE
MacOS can't find serial port

### ISSUE THREAD

**Issue by schwiet** [keyboardio/Kaleidoscope#679]
When trying to run `make flash` I get an error that it was not able to find the serial port name. I tried poking around in the `find-device-port-name` file, but I haven't used perl since I was in school and making changes to the file didn't seem to apply to subsequent runs of `make flash`
 
```
To update your keyboard's firmware, hold down the 'Prog' key on your keyboard,
and then press 'Enter'.

When the 'Prog' key glows red, you can release it.


ls: /dev/cu.usbmodem*: No such file or directory
Can't find Model 01 serial port name at /my/home/Documents/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope/bin/find-device-port-macos line 106.
make: *** [flash] Error 1
```

Perhaps the important point is that the only `tty.*` or `cu.*` entries in `/dev/` are `Bluetooth-Incoming-Port` Any ideas?

**Comment by obra** [comment]
Can you send us the output of `ls -al /dev/cu.*`?
ᐧ

**Comment by obra** [comment]
Is the Model 01 plugged directly into your computer or is there a hub
involved? If it's not showing up as a serial device, there's something
seriously wrong going on.
ᐧ

**Comment by obra** [comment]
Can you test on something other than a Hackintosh? There are all sorts of
weird driver issues that could be causing problems on such a machine.
ᐧ
