### ISSUE TITLE
Flushing firmware breaks keyboard layout on 1.9.6

### ISSUE THREAD

**Issue by AleksanderPopov** [keyboardio/Kaleidoscope#693]
*Description:* After flushing keyboard layout does not match config layout

*Pre-conditions:* 

1. Use this config https://github.com/AleksanderPopov/.dotfiles/blob/master/firmware/firmware.ino
2. Setup Arduino with 1.9.6 keyboardio board using this instruction: https://github.com/keyboardio/Kaleidoscope/wiki/Add-keyboard-support-to-Arduino
![Screen Shot 2019-10-04 at 09 14 24](https://user-images.githubusercontent.com/21224705/66185221-65899680-e687-11e9-8a1b-bfb3f2a8f012.png)

*Steps:*

1. Flush firmware

*Expected result:* keyboard layout matches the config

*Actual result:* keyboard layout looks like 
![Screen Shot 2019-10-04 at 09 23 45](https://user-images.githubusercontent.com/21224705/66185619-ad5ced80-e688-11e9-887a-21c9048d7698.png)

So layout are completely messed up, have no idea why it's happening...

*Note:* Screenshot with actual keyboard layout was taken using Chrysalis, which can understand correctly which layout is in keyboard now ( for some reason )

**Comment by AleksanderPopov** [comment]
any updates on that? it's still an issue.

**Comment by obra** [comment]
It sounds like you were coming from an older firmware with a different
EEPROM layout. In the Chrysalis settings, you should have the ability to
reset the EEPROM. That -should- do it.
ᐧ

**Comment by AleksanderPopov** [comment]
That seems to do the trick. Thank you @obra
