### ISSUE TITLE
Raise: HID report does not appear to work

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#754]
On the Raise, while everything else seems to function correctly, keyboard HID reports aren't being sent. The following code in `loop()` does not produce any HID report:

```c++
  kaleidoscope::hid::pressKey(Key_A);
  kaleidoscope::hid::sendKeyboardReport();
  delay(100);
  kaleidoscope::hid::releaseKey(Key_A);
  kaleidoscope::hid::sendKeyboardReport();
  delay(100);
```

The problem may or may not be in Kaleidoscope, KeyboardioHID would be the obvious source of the problem, but reporting it here in case it isn't KeyboardioHID.

**Comment by algernon** [comment]
The reason I'm skeptical about `KeyboardioHID` being the problem, is that when I switch to Dygma's fork of it, which works with their older Kaleidoscope fork, I still don't get any reports.

**Comment by algernon** [comment]
And its not just keyboard reports... mouse events aren't received by the host either.

**Comment by algernon** [comment]
Oh. This might end up being a HID Descriptor issue! Looks like the first thing in the descriptor is ConsumerControl. That might confuse things.

**Comment by algernon** [comment]
Hm, no, that's not it. Descriptor appears to be the same when using the factory firmware too. Darn. I had high hopes there.

**Comment by noseglasses** [comment]
It seems the whole firmware is broken. With a fresh clone of the bundle and the M01 stock firmware my keyboard shows no reaction. Maybe thats the virtual HID issue. @algernon, hadn't you fixed that (ifndef guards)?

**Comment by algernon** [comment]
I didn't add the ifdef guard yet, because the virtual hid doesn't get compiled for me. (Haven't checked the Model01 yet, mind you).

Meanwhile, I found the Raise issue, [KeyboardioHID/HID.cpp](https://github.com/keyboardio/KeyboardioHID/blob/master/src/HID.cpp#L105): we need to send that whole thing as one packet on SAMD:

```c++
    uint8_t p[64];
    p[0] = id;
    memcpy(&p[1], data, len);
    return USBDevice.send(pluggedEndpoint, p, len+1);
```

**Comment by noseglasses** [comment]
Ok, seems that's two different matters. Will submit a PR with a fix for the M01 after lunch.

**Comment by noseglasses** [comment]
> because the virtual hid doesn't get compiled for me

But why? The virtual hid is now part of the core repo. That means it is compiled unconditionally. That's why we need the `#ifdef KALEIDOSCOPE_VIRTUAL_BUILD` guards in the first place. 

Experiments show that any `.cpp` file that is added to any place below `src` in the core repo will be compiled.

**Comment by algernon** [comment]
No clue, to be honest. I didn't have time and energy to investigate yet. It might get compiled, but it is not interfering with the Raise right now. It might interfere with others, I haven't checked yet.
