### ISSUE TITLE
Clarify some deprecations

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#788]
We currently have an entry in `UPGRADING.md` about `Kaleidoscope` and `kaleidoscope::Runtime`, with an end-date in 2019. That date is probably wrong, and should've been 2020. But more important is clarifying what is deprecated and where. See [here](https://github.com/keyboardio/Kaleidoscope/issues/752#issuecomment-571429125) for some comments, but the gist of it is this question: Do we want to remove the global `Kaleidoscope` symbol, or keep it, but prefer using `kaleidoscope::Runtime` within the core firmware?

**Comment by obra** [comment]
I believe it to be the latter, but would love someone to pull out the
discussion from the pull request that added Runtime
ᐧ

**Comment by noseglasses** [comment]
> but would love someone to pull out the
discussion from the pull request that added Runtime

https://github.com/keyboardio/Kaleidoscope/pull/737#issuecomment-562672115

**Comment by algernon** [comment]
Lovely, thank you! I'll update UPGRADING.md a bit later.
