### ISSUE TITLE
Breaking change: the HID facade

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#793]
When we transitioned to HID drivers instead of using the HID facade, we also stopped including `kaleidoscope/hid.h` by default. This breaks any out-of-tree sketches that made use of the facade, including the factory firmware and its derivatives.

We've broken backwards compatibility, in short. I think we should add back the `kaleidoscope/hid.h` include to `Kaleidoscope.h`, and only remove it when we remove support for the old facade.

**Comment by obra** [comment]
Please do that and push right away
