### ISSUE TITLE
tapDanceActionKeys handling repeat on hold not working properly

### ISSUE THREAD

**Issue by dk-88** [keyboardio/Kaleidoscope#806]
This issue was created in regards to a forum [post|https://community.keyboard.io/t/tapdance-spamming-uncontrollably/3521/3].

I am running into a minor annoyance with tapdance. At first impression it seems to work but when holding the key for longer than a second it starts to spam a signgle character repeatedly which only stops after about 15 seconds.

Here is a [link](https://community.keyboard.io/uploads/short-url/tSnJsfr0uQNTthuJtyGz2vHLrYo.ino) to my sketch mapping (, [ and { to Key_LED and and Key_Any to ), ] and }.

**Comment by gedankenexperimenter** [comment]
What's happening here is that a TapDance key is being held past its timeout, and somehow causing two report per cycle, one with the keycode and one without. On my computer, the HID reports get buffered enough that I can unplug the keyboard and still get several seconds of repeating characters. I haven't been able to trace how it's happening in the code yet, but as I'm planning to rewrite TapDance completely in the near future, I'm giving up trying to figure it out for now.
