### ISSUE TITLE
Update Atreus firmware to match the layout card

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#823]
It looks like the stock firmware for the pilot run units doesn't match the layout card layout.

**Comment by obra** [comment]
![image](https://user-images.githubusercontent.com/45416/77101544-bb9f8b80-69d4-11ea-83e1-7834f0a6b670.png)

**Comment by algernon** [comment]
Oh dear. This is funny. The example _in this repo_ is correct, and matches the layout card., as of #782. However, the pilot run uses the firmware from [Chrysalis-Firmware-Bundle](https://github.com/keyboardio/Chrysalis-Firmware-Bundle/blob/fa6eabce646b036500269b36a9653294ed51d22a/Keyboardio/Atreus2/default/Atreus2.ino), which uses the layout prior to #782.

I will update that repo.
