### ISSUE TITLE
ShapeShifter -  Shift [ to ]

### ISSUE THREAD

**Issue by noctuid** [keyboardio/Kaleidoscope#828]
I have `[` bound on a layer. I want to define `[` to be `]` when shifted. I tried to do this with ShapeShifter, but I guess because the curly brace keys are defined as shifted square brackets, I get `}` instead. It would be nice if these keys and the parens were not defined as aliases using LSHIFT (if that's possible?). I also tried MagicCombo but couldn't get it to work well for this purpose.

I also haven't added too terribly much to my config but keep getting `text section exceeds available space in board` errors when running make and having to delete things. Is this expected?

**Comment by gedankenexperimenter** [comment]
ShapeShifter can change the keycode of a key when <kbd>shift</kbd> is held, but it can't remove the effect of the shift key, which changes `]` to `}` (on US QWERTY, anyway). I might try to port my UnShifter plugin to Kaleidoscope at some point, but it's still quite difficult to do. That plugin allows a key to "unshift", suppressing the held shift key's value while it's held (until some other key is pressed). It's on my TODO list, but probably requires some changes to Kaleidoscope to make it possible and/or practical.
