### ISSUE TITLE
Mouse warping does not work on ChromeOS

### ISSUE THREAD

**Issue by hnrklssn** [keyboardio/Kaleidoscope#829]
Due to lockdown I've recently taken to using my chromebook for SSHing to my workstation. However I've noticed the mouse warp keys do nothing on my chromebook. They still work on other OSs, so I'm not quite sure if the issue lies in lack of OS support, or lack of support for the platform in Kaleidoscope.

**Comment by obra** [comment]
That support requires "Absolute Mouse" graphics tablet drivers at the host OS level. At least testing here on a Samsung chromebook with a current CrOS build, I don't have those drivers. So I think it's "ChromeOS can't do that yet"
