### ISSUE TITLE
Macros plugin documentation lacks examples

### ISSUE THREAD

**Issue by tnorthcutt** [keyboardio/Kaleidoscope#836]
I just learned how to use the Macros plugin, but the process around figuring out how to use `Macros.play()` was a bit painful, since there's no example in [the README](https://github.com/keyboardio/Kaleidoscope-Macros/tree/4a77929a26f6f463c7b78277fed6f3f2b5244a1a).

It would be great to be able to add an example to that repo, but since it's archived it's not possible to create a PR for it.

Here's a thread with more context: https://community.keyboard.io/t/getting-started-with-macros-key-combinations/3830

**Comment by algernon** [comment]
The plugin, along with its documentation, has been merged into Kaleidoscope. Current docs are at [docs/plugins/Macros.md](https://github.com/keyboardio/Kaleidoscope/blob/master/docs/plugins/Macros.md), so you can create a PR against this repo! :)
