### ISSUE TITLE
Documentation for creating your dev environment is wrong

### ISSUE THREAD

**Issue by sboesebeck** [keyboardio/Kaleidoscope#838]
I was trying to get a local dev environment up and running. This is not really working, I also followed the instructions https://github.com/keyboardio/Kaleidoscope/wiki/Setting-up-a-development-environment and https://github.com/keyboardio/Kaleidoscope

I am talking about the MacOs Version here, did not try with windows or linux yet. 

- the path for Arduino sketch books is in Document, but the Hardware sources seem to be in ~/Library/Arduino15/packages ... - the directory structure does not match the one in the kaleidoscope git project
- when checking out the kaleidoscope bundle with all submodules, the compiling uses the Arduino Libraries. That means, even if there was an update in the kaleidoscope sources, it is not used. it links automatically to ~/Library/Arduino15/packages/keyboardio/hardware/avr/1.96.0/

I would try to fix the documentation, but I could not make it use the right resources, so I do not know the right way to do it.

**Comment by obra** [comment]
Hi,

You should -not- be installing into ~/Library/Arduino15 by hand. That’s the place Arduino’s package manger installs prebuilt packages.  

Indeed, Arduino prefers pre-built packages from their boards manager to local versions in Documents/Arduino.

I believe the correct instructions are to -uninstall- the Boards Manager-managed package (using the Arduino Boards Manager) before doing a git checkout. 

Can you see if that works?

**Comment by sboesebeck** [comment]
yes... thanks. That did the trick, it now uses the correct path. 

So the documentation is not wrong, just that little hint is missing...

**Comment by obra** [comment]
If you felt like sending a PR for the hint, I’m sure it’d help other folks out :)

**Comment by sboesebeck** [comment]
I am already on it! 😉

**Comment by sboesebeck** [comment]
I was able to directly edit the page... Hope i did not miss some 
important things 😉

https://github.com/keyboardio/Kaleidoscope/wiki/Setting-up-a-development-environment

**Comment by obra** [comment]
Urk. It looks like there are some factual issues, a bunch of removed
information, and a bunch of now macOS-specific information in the update.
I'll see about unwinding that.

**Comment by sboesebeck** [comment]
Well, before it was also quite MacOS specific with a lot of things 
marked as "TODO" and alike...

I cannot say anything about windows - if it had been there before, I 
would have left it there.

**Comment by obra** [comment]
Don't sweat it :)
