### ISSUE TITLE
make docker-simulator-tests doesn't detect changes to testing infrastructure code

### ISSUE THREAD

**Issue by obra** [keyboardio/Kaleidoscope#942]
changes to things inside testing/ don't get properly rebuilt if modified in between runs to "make docker-simulator-tests"

**Comment by gedankenexperimenter** [comment]
I think sometimes changes to code in Kaleidoscope also don't trigger rebuilds of the appropriate source files. When I was working on it last night, I sometimes got linker errors if I didn't wipe out the whole `_build/` directory first.

**Comment by obra** [comment]
I've found the cause and am testing a fix for this one.
