### ISSUE TITLE
A subtle issue with layer states

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#951]
When trying to figure out what happened in keyboardio/Chrysalis#599, I stumbled upon a subtle bug in the layer state handling code. When Kaleidoscope starts up, we set `active_layer_count_` to `1`, and clear `active_layers_` and `layer_state_`. In practice, this means that layer 0 will both be active and not. It will be active as far as lookup is concerned, because the active layer count is 1, and the first entry in `active_layers_` is 0. However, `isActive(0)` will report false, because `layer_state_` is completely clear, and we do _not_ flip layer 0's bit open.

In practice, this shouldn't cause any issues, but it's inconsistent. We should be setting up `layer_state_` properly in the beginning too. One way to do that would be an explicit activation, but that would invoke the `onLayerChange()` hook, which we do not want at startup. We could have a `Layer::setup()` method that does any initial setup, including flipping a bit on. We could also have `updateActiveLayers()` recompute `layer_state_` too.

I'm leaning towards `Layer::setup()`, because that's more future-proof. We have a setup method for most other components of the firmware, we should have one for layers too. That would remove the slightly awkward keymap cache update from `Runtime::setup()`, as it would get replaced by `Layer.setup()` instead.

**Comment by obra** [comment]
Can we start with a failing test?

**Comment by algernon** [comment]
I _think_ I can even write a test for this, if I'm a bit clever. Since we want to test `Layer.isActive(0)`, and we can't reach that directly from the tests, we'll use a macro in the test sketch, that does different things based on whether the function returns true or false. Then we can examine the report after.

So yep, we can start with a failing test.

**Comment by gedankenexperimenter** [comment]
Are you sure you can't reach that directly from the testcase?

**Comment by gedankenexperimenter** [comment]
I just tried it out, and I can write a test for this, quite simply, without resorting to Macros.
