### ISSUE TITLE
Error in a web adresse on the doc

### ISSUE THREAD

**Issue by Myrddinlefou** [keyboardio/Kaleidoscope#963]
Hello,

The web adress of the Tar archive: http://arduino.cc/download are false now, it is a https site.

https://kaleidoscope.readthedocs.io/en/latest/setup_toolchain.html#set-up-the-arduino-ide

Have a good day

Myrddin

**Comment by obra** [comment]
Thanks so much for reporting this. I think that part of what you're seeing is that Arduino has been the subject of a sustained DDOS attack this week. I can't get there as either an http or an https site

**Comment by obra** [comment]
(The original URL once again works)
